# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/solving-2048',
                'doc_host': 'https://Jason-XII.github.io',
                'git_url': 'https://github.com/Jason-XII/solving-2048',
                'lib_path': 'solving_2048'},
  'syms': {'solving_2048.core': {'solving_2048.core.foo': ('core.html#foo', 'solving_2048/core.py')}}}
